/**
 * Portfolio registry — single source of truth.
 *
 * The hub is organized by problem area and proof level, not by repo count.
 * Every public item should answer three questions:
 *   - evidence: what is locally verifiable?
 *   - constraint: what must not be over-claimed?
 *   - status: shipped / active / lab / archive / hold
 */

export default {
  owner: 'heznpc',

  meta: {
    name: 'heznpc',
    tagline: 'Systems across AI, trust, local tools, and cultural data',
    bio: 'Heznpc builds small, inspectable systems that turn messy workflows into usable tools.',
    thesis:
      'This hub is a portfolio map, not a repo dump. Work is grouped by the problem it proves: ' +
      'AI learning localization, local trust, developer presentation, local-first workflow tools, ' +
      'cultural archives, marketplace experiments, and future physical-computing systems.',
    github: 'https://github.com/heznpc',
    contact: 'https://github.com/heznpc',
  },

  areas: [
    {
      id: 'ai-learning-localization',
      label: 'AI learning localization',
      summary: 'Browser-based learning tools where translation, glossary control, and tutor UX need to stay bounded.',
      current: 'Use course-specific flows as proof, not generic translation claims.',
      frontier: 'Evaluation, permission hygiene, and first-user proof before stronger public claims.',
      projectIds: ['skillbridge'],
    },
    {
      id: 'trust-local-diagnostics',
      label: 'Trust and local diagnostics',
      summary: 'Local checks that explain risk without turning the user machine into a telemetry source.',
      current: 'Prefer readable reports, opt-in lookups, and artifact hygiene over broad security promises.',
      frontier: 'Local device trust, agent-tool governance, and privacy-preserving diagnostics.',
      projectIds: ['pc-health-check'],
    },
    {
      id: 'developer-presence',
      label: 'Developer presence and publishing',
      summary: 'Composable presentation surfaces for code, docs, and project evidence.',
      current: 'Show verified artifacts and examples instead of rankings or soft metrics.',
      frontier: 'A portfolio layer that stays current without inflating unfinished work.',
      projectIds: ['profilekit'],
    },
    {
      id: 'local-first-workflows',
      label: 'Local-first workflow tools',
      summary: 'Small utilities for private work queues, reversible file operations, and personal automation.',
      current: 'Keep these as lab proof until restore, install, and synthetic demo paths are clean.',
      frontier: 'Human-controlled tools that can later bridge into physical and edge workflows.',
      projectIds: ['aispool', 'mothball'],
    },
    {
      id: 'cultural-data-archives',
      label: 'Cultural data and archive UX',
      summary: 'Static and mobile-first viewers for niche datasets where provenance and scope matter.',
      current: 'Useful as UX/data examples, not as central product claims.',
      frontier: 'Clear source boundaries, mobile proof, and better refresh evidence.',
      projectIds: ['tr-story', 'tr-archive', 'hello-project'],
    },
    {
      id: 'marketplace-experiments',
      label: 'Marketplace experiments',
      summary: 'Trust-heavy product ideas that are still below service-ready evidence.',
      current: 'Do not present as launched services until payment, dispute, and safety flows are verified.',
      frontier: 'Narrow state-machine prototypes before any public marketplace framing.',
      projectIds: ['dol-pin'],
    },
    {
      id: 'physical-computing-frontier',
      label: 'Physical computing frontier',
      summary: 'Future work at the boundary of local software, sensing, devices, and edge intelligence.',
      current: 'Direction only; no representative repo is claimed yet.',
      frontier: 'IoT and physical-system work should inherit the same local trust and evidence rules.',
      projectIds: [],
    },
  ],

  projects: [
    {
      repo: 'skillBridge',
      category: 'selected',
      displayTier: 'hero',
      area: 'ai-learning-localization',
      status: 'active',
      tier: 1,
      emoji: '🌐',
      tags: ['Extension', 'Learning', 'i18n'],
      description: 'Course-focused browser extension for translation, glossary control, and inline tutor flows.',
      evidence: 'Large local quality surface: unit tests, lint, formatting, locale checks, screenshots, and release scripts.',
      constraint: 'Public listing, region availability, and latest released version must be verified before claiming traction.',
    },
    {
      repo: 'ProfileKit',
      owner: 'starter-series',
      category: 'selected',
      displayTier: 'case-study',
      area: 'developer-presence',
      status: 'shipped',
      tier: 1,
      emoji: '🪪',
      tags: ['SVG', 'README', 'API'],
      description: 'Composable SVG profile and project cards by URL.',
      evidence: 'Local checks and tests cover rendering, URL safety, and endpoint behavior.',
      constraint: 'Canonical hosting and some endpoint docs need freshness checks before stronger adoption claims.',
    },
    {
      repo: 'pc-health-check',
      private: true,
      category: 'selected',
      displayTier: 'case-study',
      area: 'trust-local-diagnostics',
      status: 'shipped',
      tier: 1,
      emoji: '🩺',
      tags: ['Local', 'Diagnostics', 'Privacy'],
      description: 'Local PC diagnostic reports for compatibility and trust checks.',
      evidence: 'Rule tests and release smoke checks exist, with a local-first report model.',
      constraint: 'Public examples should use sanitized output and avoid implying a complete security product.',
    },
    {
      repo: 'TR-STORY',
      owner: 'Tales-Runner',
      category: 'area-proof',
      displayTier: 'area-proof',
      area: 'cultural-data-archives',
      status: 'active',
      tier: 2,
      emoji: '📖',
      tags: ['Static', 'Mobile UX', 'Archive'],
      description: 'Mobile-first story viewer for a bounded cultural archive.',
      evidence: 'Static export, data snapshot, and basic tests are present.',
      constraint: 'External content boundaries and data freshness need to stay visible.',
    },
    {
      repo: 'TR-archive',
      id: 'tr-archive',
      owner: 'Tales-Runner',
      category: 'area-proof',
      displayTier: 'area-proof',
      area: 'cultural-data-archives',
      status: 'repair',
      tier: 3,
      emoji: '🎮',
      tags: ['Archive', 'Search', 'PWA'],
      description: 'Fan-archive style viewer and utility surface with search and static data flows.',
      evidence: 'Route breadth, headers, search, and app structure are substantial.',
      constraint: 'Current local test failures and unofficial-content boundaries keep it below case-study level.',
    },
    {
      repo: 'AcademyLens',
      id: 'academy-lens',
      category: 'lab',
      displayTier: 'lab',
      area: 'ai-learning-localization',
      status: 'beta',
      tier: 3,
      emoji: '🔎',
      tags: ['Extension', 'Beta', 'Glossary'],
      description: 'Sibling experiment for course-page translation and terminology preservation.',
      evidence: 'Local static checks and unit tests exist.',
      constraint: 'Still a beta/local-install project; store readiness and live QA should not be implied.',
    },
    {
      repo: 'aispool',
      private: true,
      category: 'lab',
      displayTier: 'lab',
      area: 'local-first-workflows',
      status: 'lab',
      tier: 3,
      emoji: '🧵',
      tags: ['CLI', 'Local', 'Workflow'],
      description: 'Local inbox for reviewing and promoting AI-work session candidates.',
      evidence: 'Small CLI and tests exist with local-only data assumptions.',
      constraint: 'Any public demo must be synthetic; real local metadata should never be shown.',
    },
    {
      repo: 'mothball',
      private: true,
      category: 'lab',
      displayTier: 'lab',
      area: 'local-first-workflows',
      status: 'pre-alpha',
      tier: 3,
      emoji: '📦',
      tags: ['Swift', 'Archiver', 'Restore'],
      description: 'Git-aware project archiver exploring reversible cleanup flows.',
      evidence: 'Swift package structure and restore round-trip tests are present.',
      constraint: 'Pre-alpha and file-operation-adjacent; not an end-user cleaner yet.',
    },
    {
      repo: 'heznpc-archive',
      id: 'cuk-sw-community',
      name: 'cuk-sw-community',
      category: 'archive',
      displayTier: 'archive',
      area: 'local-first-workflows',
      status: 'archive',
      tier: 3,
      emoji: '🗃️',
      tags: ['Archive', 'RLS', 'Admin'],
      description: 'Community-app skeleton being reframed as an owner-write archive.',
      evidence: 'Auth, storage, rate-limit, and archive-mode code paths exist.',
      constraint: 'Do not describe it as a live community service.',
    },
    {
      repo: 'dol-pin',
      private: true,
      category: 'lab',
      displayTier: 'hold',
      area: 'marketplace-experiments',
      status: 'hold',
      tier: 4,
      emoji: '🐬',
      tags: ['Marketplace', 'Trust', 'Mobile'],
      description: 'C2C rental marketplace prototype for event goods.',
      evidence: 'Planning, app structure, and trust-flow code exist.',
      constraint: 'Payment, dispute, safety, and dirty-worktree risks keep it out of the public front layer.',
    },
    {
      repo: 'hello-project',
      category: 'archive',
      displayTier: 'archive',
      area: 'cultural-data-archives',
      status: 'archive',
      tier: 3,
      emoji: '🎤',
      tags: ['Timeline', 'Data', 'Archive'],
      description: 'Closed-scope cultural timeline visualization.',
      evidence: 'Static visualization and scoped dataset exist.',
      constraint: 'Best kept as archive proof unless provenance and mobile proof are refreshed.',
    },
  ],

  starters: [
    { owner: 'starter-series', repo: 'docker-deploy-starter', deployTo: 'VPS' },
    { owner: 'starter-series', repo: 'browser-extension-starter', deployTo: 'Browser stores' },
    { owner: 'starter-series', repo: 'discord-bot-starter', deployTo: 'Hosted runtime' },
    { owner: 'starter-series', repo: 'telegram-bot-starter', deployTo: 'Hosted runtime' },
    { owner: 'starter-series', repo: 'react-native-starter', deployTo: 'Mobile stores' },
    { owner: 'starter-series', repo: 'electron-app-starter', deployTo: 'Desktop' },
    { owner: 'starter-series', repo: 'vscode-extension-starter', deployTo: 'Editor marketplace' },
    { owner: 'starter-series', repo: 'npm-package-starter', deployTo: 'Package registry' },
    { owner: 'starter-series', repo: 'mcp-server-starter', deployTo: 'Package registry' },
    { owner: 'starter-series', repo: 'python-mcp-server-starter', deployTo: 'Package registry' },
    { owner: 'starter-series', repo: 'cloudflare-pages-starter', deployTo: 'Static hosting' },
  ],
};
